# Generated by Django 5.2.8 on 2025-11-18 18:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='unknown', max_length=100)),
                ('Species', models.CharField(default='unknown', max_length=50)),
                ('Breed', models.CharField(default='unknown', max_length=100)),
                ('Age', models.IntegerField(default=0)),
                ('Gender', models.CharField(default='unknown', max_length=10)),
                ('Status', models.CharField(default='available', max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='unknown', max_length=100)),
                ('Location', models.CharField(default='unknown', max_length=150)),
                ('Contact', models.CharField(default='unknown', max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='unknown', max_length=100)),
                ('Specialization', models.CharField(default='general', max_length=100)),
                ('Contact', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ADOPTER', 'Adopter'), ('DONATOR', 'Donator')], default='ADOPTER', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='core_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='core_user_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vaccine', models.CharField(default='unknown', max_length=100)),
                ('Treatment', models.CharField(default='unknown', max_length=200)),
                ('RecordDate', models.DateField(auto_now_add=True)),
                ('Pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='core.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdoptionDate', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(default='pending', max_length=20)),
                ('Adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to=settings.AUTH_USER_MODEL)),
                ('Pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='core.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='Shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.shelter'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('DonationDate', models.DateField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('Shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='VetAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppointmentDate', models.DateField(auto_now_add=True)),
                ('Reason', models.CharField(default='Checkup', max_length=200)),
                ('Notes', models.TextField(default='')),
                ('Pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_appointments', to='core.pet')),
                ('Vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.veterinarian')),
            ],
        ),
    ]
